services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: brain_backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    networks:
      - brain_network


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: brain_frontend
    restart: unless-stopped

    env_file:
      - .env

    environment:
      BACKEND_URL: http://backend:8000

    depends_on:
      - backend

    ports:
      - "8501:8501"

    networks:
      - brain_network


networks:
  brain_network:
    driver: bridge