FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-frontend.txt .

RUN pip install --upgrade pip

RUN pip install --default-timeout=1000 --retries 20 --no-cache-dir -r requirements-frontend.txt

COPY . .

EXPOSE 8501

CMD ["sh", "-c", "streamlit run frontend/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.fileWatcherType=none"]