import os

from datetime import datetime

from reportlab.lib import colors

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.platypus import (

    SimpleDocTemplate,

    Paragraph,

    Spacer,

    Image,

    Table,

    TableStyle

)

REPORT_FOLDER = "reports"

os.makedirs(

    REPORT_FOLDER,

    exist_ok=True

)


def generate_report(

    filename: str,

    prediction: str,

    confidence: float,

    gradcam_path: str,

    user_email: str

):

    """
    Generate a professional PDF report.

    Returns
    -------

    report_path
    """

    timestamp = datetime.now().strftime(

        "%Y%m%d_%H%M%S"

    )

    report_name = f"report_{timestamp}.pdf"

    report_path = os.path.join(

        REPORT_FOLDER,

        report_name

    )

    document = SimpleDocTemplate(

        report_path

    )

    styles = getSampleStyleSheet()

    story = []

    title = Paragraph(

        "<b><font size=18>Brain Tumor Detection Report</font></b>",

        styles["Title"]

    )

    story.append(

        title

    )

    story.append(

        Spacer(1, 20)

    )

    table_data = [

        [

            "Patient Email",

            user_email

        ],

        [

            "MRI File",

            filename

        ],

        [

            "Prediction",

            prediction

        ],

        [

            "Confidence",

            f"{confidence:.2f}%"

        ],

        [

            "Generated On",

            datetime.now().strftime(

                "%d-%m-%Y %H:%M:%S"

            )

        ]

    ]

    table = Table(

        table_data,

        colWidths=[150, 300]

    )

    table.setStyle(

        TableStyle(

            [

                (

                    "BACKGROUND",

                    (0, 0),

                    (-1, 0),

                    colors.lightgrey

                ),

                (

                    "GRID",

                    (0, 0),

                    (-1, -1),

                    1,

                    colors.black

                ),

                (

                    "BACKGROUND",

                    (0, 0),

                    (0, -1),

                    colors.whitesmoke

                ),

                (

                    "FONTNAME",

                    (0, 0),

                    (-1, -1),

                    "Helvetica"

                ),

                (

                    "BOTTOMPADDING",

                    (0, 0),

                    (-1, -1),

                    10

                )

            ]

        )

    )

    story.append(

        table

    )

    story.append(

        Spacer(1, 20)

    )

    if (

        gradcam_path is not None

        and

        os.path.exists(

            gradcam_path

        )

    ):

        story.append(

            Paragraph(

                "<b>Grad-CAM Visualization</b>",

                styles["Heading2"]

            )

        )

        story.append(

            Spacer(1, 10)

        )

        image = Image(

            gradcam_path,

            width=300,

            height=300

        )

        story.append(

            image

        )

        story.append(

            Spacer(1, 20)

        )

    story.append(

        Paragraph(

            "<b>Generated By</b>",

            styles["Heading2"]

        )

    )

    story.append(

        Paragraph(

            "Brain Tumor Detection System",

            styles["Normal"]

        )

    )

    document.build(

        story

    )

    return report_path